name: On Release - Verify & Announce

on:
  release:
    types: [published]

jobs:
  verify-release:
    name: Verify Uploaded Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (required by GitHub CLI)
        uses: actions/checkout@v3

      - name: Install GitHub CLI and tools
        run: |
          sudo apt update
          sudo apt install -y gh dpkg rpm

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Print release info
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release name: ${{ github.event.release.name }}"

      - name: Download release assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir assets
          cd assets
          gh release download ${{ github.event.release.tag_name }}

      - name: Inspect .deb files
        run: |
          echo "Inspecting .deb packages..."
          for file in assets/*.deb; do
            echo ":: Inspecting $file ::"
            dpkg-deb --info "$file" || true
            dpkg-deb --contents "$file" || true
          done

      - name: Inspect .rpm files
        run: |
          echo "Inspecting .rpm packages..."
          for file in assets/*.rpm; do
            echo ":: Inspecting $file ::"
            rpm -qpi "$file" || true
          done

      - name: Finish
        run: echo "✅ CI/CD pipeline completed for release tag ${{ github.event.release.tag_name }}"
